name: Hello World
on: push
jobs:
  hello-job:
    name: Hello Job
    runs-on: ubuntu-latest
    steps:
    - name: Echo text
      run: echo "Hello, world!"
    - name: checkout
      uses: actions/checkout@v3
    - name: lists files
      run: ls -ltr
    - name: create files
      run: echo "new file created" > text.txt
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: text.txt
  next-job:
    name: secondjob
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
      - name: print downloaded file
        run: cat text.txt
